/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerPerceptron;
import javax.swing.JOptionPane;

/**
 *
 * @author Willian
 */
public class ViewPerceptron extends javax.swing.JFrame {

    /**
     * Creates new form ViewPerceptron
     */
    public ViewPerceptron() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textPontos = new javax.swing.JLabel();
        campoPontos = new javax.swing.JTextField();
        textReta = new javax.swing.JLabel();
        campoA = new javax.swing.JTextField();
        campoB = new javax.swing.JTextField();
        campoC = new javax.swing.JTextField();
        textX = new javax.swing.JLabel();
        textY = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        textResultado = new javax.swing.JLabel();
        textAprendizado = new javax.swing.JLabel();
        campoN = new javax.swing.JTextField();
        campoResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perceptron");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perceptron", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N
        jPanel1.setToolTipText("");

        textPontos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        textPontos.setText("Informe o txt com os pontos:");

        textReta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        textReta.setText("Informe os pontos da reta :");

        campoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAActionPerformed(evt);
            }
        });

        campoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBActionPerformed(evt);
            }
        });

        campoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCActionPerformed(evt);
            }
        });

        textX.setText("x ");

        textY.setText("y =");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        textResultado.setText("Resultado:");

        textAprendizado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        textAprendizado.setText("Informe a taxa de aprendizado:");

        campoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNActionPerformed(evt);
            }
        });

        campoResultado.setEditable(false);
        campoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOk)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPontos)
                            .addComponent(textReta))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(textX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoPontos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textAprendizado)
                            .addComponent(textResultado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97))
                            .addComponent(campoResultado)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnCancelar)))
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPontos)
                    .addComponent(campoPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textReta)
                    .addComponent(campoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textX)
                    .addComponent(textY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAprendizado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textResultado))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCActionPerformed

    private void campoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBActionPerformed

    private void campoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // botao cancelar
        campoPontos.setText("");
        campoA.setText("");
        campoB.setText("");
        campoC.setText("");
        campoN.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // botao OK
        String caminho = campoPontos.getText();
        String A       = campoA.getText();
        String B       = campoB.getText();
        String C       = campoC.getText();
        String N       = campoN.getText();
        if (caminho.isEmpty())//se caminho vazio aparece a mensagem
            JOptionPane.showMessageDialog(null, "ERRO!! Campo dos pontos está vazio", "Perceptron", 0);
        else if(campoN.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "ERRO!! Taxa de aprendizado deve ser um número entre 0 e 1", "Perceptron", 0);
        else{
            if(!caminho.contains(".txt"))//se caminho não tiver .txt adiciona-o
                caminho+=".txt";
            if(A.contains(","))//trata a , no campoA
                A = A.replace(",", ".");
            if(B.contains(","))//trata a , no campoA
                B = B.replace(",", ".");
            if(C.contains(","))//trata a , no campoA
                C = C.replace(",", ".");
            if(N.contains(","))//trata a , no campoA
                N = N.replace(",", ".");
            if(campoA.getText().isEmpty())//se campoA vazio passa ele como zero
                campoA.setText("0");
            if(campoB.getText().isEmpty())//se campoB vazio passa ele como zero
                campoB.setText("0");
            if(campoC.getText().isEmpty())//se campoC vazio passa ele como zero
                campoC.setText("0");
            try{
                if(Float.parseFloat(N)<= 0 || Float.parseFloat(N)>1)
                    JOptionPane.showMessageDialog(null, "ERRO!! Taxa de aprendizado deve ser um número entre 0 e 1", "Perceptron", 0);
                else{
                    float a = Float.parseFloat(A);//converte de String pra float o ponto A
                    float b = Float.parseFloat(B);//converte de String pra float o ponto B
                    float c = Float.parseFloat(C);//converte de String pra float o ponto C
                    float n = Float.parseFloat(N);//converte de String pra float a taxa de aprendizado N
                    ControllerPerceptron cp = new ControllerPerceptron (caminho, a, b, c, n);
                    campoResultado.setText(cp.perceptron());
                }
            }catch(NumberFormatException e){//caso tenha erro na conversão aparece a mensagem
                JOptionPane.showMessageDialog(null, "ERRO!! Campos da reta e da taxa de aprendizado"+
                        " devem contonter apenas números", "Perceptron", 0);
            }//fi catch
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void campoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNActionPerformed

    private void campoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPerceptron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPerceptron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPerceptron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPerceptron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPerceptron().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JTextField campoA;
    private javax.swing.JTextField campoB;
    private javax.swing.JTextField campoC;
    private javax.swing.JTextField campoN;
    private javax.swing.JTextField campoPontos;
    private javax.swing.JTextField campoResultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textAprendizado;
    private javax.swing.JLabel textPontos;
    private javax.swing.JLabel textResultado;
    private javax.swing.JLabel textReta;
    private javax.swing.JLabel textX;
    private javax.swing.JLabel textY;
    // End of variables declaration//GEN-END:variables
}
